version: '3.3'

services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile
    env_file:
      - ./project/.env
    volumes: 
      - ./project:/project
      - static:/project/static 
      - media:/project/media 
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb
    restart: always

  mysqldb:
    image: mysql:latest
    env_file:
      - ./project/.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${MYSQL_DATABASE}              
      MYSQL_USER: ${MYSQL_USER}                      
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             
    restart: always

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - mysqldb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - media:/media
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always

volumes:
  static:
  media: 
